#!/usr/bin/env bash
# Write packages/client/.env from CloudFormation stack outputs (after deploy).
# Usage: ./scripts/sync-client-env.sh [stage] [client-env-path]

set -euo pipefail

STAGE="${1:-dev}"
SERVICE="photostore-learn"
STACK="${SERVICE}-${STAGE}"
REGION="${AWS_REGION:-us-east-1}"
CLIENT_ENV="${2:-$(cd "$(dirname "$0")/../.." && pwd)/client/.env}"
SNAPSHOT_DIR="$(cd "$(dirname "$0")/.." && pwd)/.deploy"

mkdir -p "$SNAPSHOT_DIR"

outputs_json="$(aws cloudformation describe-stacks \
  --region "$REGION" \
  --stack-name "$STACK" \
  --query 'Stacks[0].Outputs' \
  --output json)"

snapshot_file="${SNAPSHOT_DIR}/outputs-${STAGE}.json"
echo "$outputs_json" >"$snapshot_file"

get_output() {
  local key="$1"
  echo "$outputs_json" | jq -r --arg k "$key" '.[] | select(.OutputKey==$k) | .OutputValue'
}

API_URL="$(get_output HttpApiUrl)"
USER_POOL_ID="$(get_output UserPoolId)"
CLIENT_ID="$(get_output UserPoolClientId)"
IDENTITY_POOL_ID="$(get_output IdentityPoolId)"

if [[ -z "$API_URL" || -z "$USER_POOL_ID" || -z "$CLIENT_ID" || -z "$IDENTITY_POOL_ID" ]]; then
  echo "Missing outputs. Is stack ${STACK} deployed in ${REGION}?" >&2
  echo "Snapshot saved to ${snapshot_file}" >&2
  exit 1
fi

mkdir -p "$(dirname "$CLIENT_ENV")"

cat >"$CLIENT_ENV" <<EOF
# Generated by photostore/scripts/sync-client-env.sh ($(date -u +"%Y-%m-%dT%H:%M:%SZ"))
# Stack: ${STACK} (${REGION})
VITE_API_URL=${API_URL}
VITE_USER_POOL_ID=${USER_POOL_ID}
VITE_USER_POOL_CLIENT_ID=${CLIENT_ID}
VITE_IDENTITY_POOL_ID=${IDENTITY_POOL_ID}
VITE_AWS_REGION=${REGION}
EOF

echo "Wrote ${CLIENT_ENV}"
echo "Snapshot: ${snapshot_file}"
